DROP TABLE IF EXISTS stock_history;
DROP TABLE IF EXISTS stocks;

CREATE TABLE stocks (
    ticker VARCHAR(10) PRIMARY KEY,
    company_name TEXT,
    sector TEXT,
    industry TEXT,
    market_index TEXT,
    price NUMERIC,
    price_change_pct NUMERIC,
    prev_close NUMERIC,
    volume BIGINT,
    market_cap BIGINT,
    enterprise_value BIGINT,
    pe_ratio NUMERIC,
    forward_pe NUMERIC,
    peg_ratio NUMERIC,
    ps_ratio NUMERIC,
    pb_ratio NUMERIC,
    pc_ratio NUMERIC,
    pfcf_ratio NUMERIC,
    ev_sales NUMERIC,
    ev_ebitda NUMERIC,
    profit_margin_pct NUMERIC,
    operating_margin_pct NUMERIC,
    gross_margin_pct NUMERIC,
    roe_pct NUMERIC,
    roa_pct NUMERIC,
    roi_pct NUMERIC,
    roic_pct NUMERIC,
    eps_ttm NUMERIC,
    eps_growth_ttm_pct NUMERIC,
    revenue_growth_ttm_pct NUMERIC,
    eps_growth_next_y_pct NUMERIC,
    eps_growth_next_5y_pct NUMERIC,
    eps_next_q NUMERIC,
    eps_this_y NUMERIC,
    eps_past_3y_pct NUMERIC,
    eps_past_5y_pct NUMERIC,
    sales_past_3y_pct NUMERIC,
    sales_past_5y_pct NUMERIC,
    sales_qyq_pct NUMERIC,
    eps_qoq_pct NUMERIC,
    rsi NUMERIC,
    beta NUMERIC,
    atr NUMERIC,
    volatility_week_pct NUMERIC,
    volatility_month_pct NUMERIC,
    rel_volume NUMERIC,
    avg_volume BIGINT,
    week_52_high NUMERIC,
    week_52_high_pct NUMERIC,
    week_52_low NUMERIC,
    week_52_low_pct NUMERIC,
    sma20 NUMERIC,
    sma50 NUMERIC,
    sma200 NUMERIC,
    insider_own_pct NUMERIC,
    insider_trans_pct NUMERIC,
    inst_own_pct NUMERIC,
    inst_trans_pct NUMERIC,
    shares_outstanding BIGINT,
    shares_float BIGINT,
    short_float_pct NUMERIC,
    short_ratio NUMERIC,
    short_interest BIGINT,
    debt_to_equity NUMERIC,
    lt_debt_to_equity NUMERIC,
    current_ratio NUMERIC,
    quick_ratio NUMERIC,
    cash_per_share NUMERIC,
    book_per_share NUMERIC,
    dividend_yield_pct NUMERIC,
    dividend_ttm NUMERIC,
    dividend_est NUMERIC,
    dividend_yield_est_pct NUMERIC,
    payout_ratio_pct NUMERIC,
    ex_dividend_date TEXT,
    dividend_gr_3y_pct NUMERIC,
    dividend_gr_5y_pct NUMERIC,
    eps_surprise_pct NUMERIC,
    sales_surprise_pct NUMERIC,
    target_price NUMERIC,
    recommendation NUMERIC,
    perf_week_pct NUMERIC,
    perf_month_pct NUMERIC,
    perf_quarter_pct NUMERIC,
    perf_half_y_pct NUMERIC,
    perf_year_pct NUMERIC,
    perf_ytd_pct NUMERIC,
    perf_3y_pct NUMERIC,
    perf_5y_pct NUMERIC,
    perf_10y_pct NUMERIC,
    employees INTEGER,
    ipo_date TEXT,
    earnings_date TEXT,
    income NUMERIC,
    sales NUMERIC,
    option_short TEXT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock_history (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    price NUMERIC,
    market_cap BIGINT,
    volume BIGINT,
    pe_ratio NUMERIC,
    ps_ratio NUMERIC,
    pb_ratio NUMERIC,
    profit_margin_pct NUMERIC,
    revenue_growth_ttm_pct NUMERIC,
    rsi NUMERIC,
    beta NUMERIC,
    insider_own_pct NUMERIC,
    inst_own_pct NUMERIC,
    debt_to_equity NUMERIC,
    target_price NUMERIC,
    recommendation NUMERIC,
    perf_week_pct NUMERIC,
    perf_month_pct NUMERIC,
    perf_quarter_pct NUMERIC,
    perf_year_pct NUMERIC,
    scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ticker, date)
);

CREATE INDEX idx_sector ON stocks(sector);
CREATE INDEX idx_industry ON stocks(industry);
CREATE INDEX idx_market_cap ON stocks(market_cap);
CREATE INDEX idx_pe_ratio ON stocks(pe_ratio);
CREATE INDEX idx_rsi ON stocks(rsi);
CREATE INDEX idx_price ON stocks(price);
CREATE INDEX idx_history_ticker ON stock_history(ticker);
CREATE INDEX idx_history_date ON stock_history(date);